In [2]:
#Import everything 

import pandas as pd
import numpy as np
import requests
import json
from bs4 import BeautifulSoup
import csv

import matplotlib.pyplot as plt
plt.style.use('seaborn')

In [3]:
f = open('/Users/markdetiberiis/MovieMonths/movie_titles.csv')
csv_f = csv.reader(f)

In [4]:
#In itialize csv contents in a list called titles

movie_df = pd.read_csv('/Users/markdetiberiis/MovieMonths/movie_df.csv')
movie_df.head()

,Unnamed: 0,Unnamed: 0.1,tconst,primary_title,runtime_minutes,genres,averagerating,numvotes,id,production_budget,domestic_gross,worldwide_gross,release_month,release_day,release_year
0,0,0,tt0249516,Foodfight,91.0,"Action,Animation,Comedy",1.9,8248,26,45000000,0,73706,Dec,31,2012
1,1,1,tt0326592,The_Overnight,88.0,NaN,7.5,24,21,200000,1109808,1165996,Jun,19,2015
2,2,2,tt3844362,The_Overnight,79.0,"Comedy,Mystery",6.1,14828,21,200000,1109808,1165996,Jun,19,2015
3,3,3,tt0337692,On_the_Road,124.0,"Adventure,Drama,Romance",6.1,37886,17,25000000,720828,9313302,Mar,22,2013
4,4,4,tt4339118,On_the_Road,89.0,Drama,6.0,6,17,25000000,720828,9313302,Mar,22,2013

In [5]:
with open('/Users/markdetiberiis/MovieMonths/movie_titles.csv', newline='') as f:
    reader = csv.reader(f)
    titles = list(reader)

#print(titles)

In [6]:
len(titles)

2876

In [7]:
new_list = []
for v in titles:
    new_list.append(v[0])

In [8]:
counter = 0

for title in new_list:
    counter += 1
    
print(counter)

2876

In [10]:
count = counter - 1
count

2875

In [11]:
counte = 0
while counte <= len(new_list):
    reviews_df['primary_title'] = movie_df['primary_title'][counte]

NameError: name 'reviews_df' is not defined

In [276]:
titles

[['primary_title'],
 ['Foodfight'],
 ['The_Overnight'],
 ['The_Overnight'],
 ['On_the_Road'],
 ['On_the_Road'],
 ['On_the_Road'],
 ['The_Secret_Life_of_Walter_Mitty'],
 ['A_Walk_Among_the_Tombstones'],
 ['Jurassic_World'],
 ['The_Rum_Diary'],
 ['The_Three_Stooges'],
 ['Andersons_Cross'],
 ['Tangled'],
 ['John_Carter'],
 ['Action_Jackson'],
 ['Dinner_for_Schmucks'],
 ['The_A-Team'],
 ['The_Possession'],
 ['Real_Steel'],
 ['The_Giver'],
 ['Toy_Story_3'],
 ['Alita_Battle_Angel'],
 ['Lincoln'],
 ['Before_We_Go'],
 ['Before_We_Go'],
 ['The_History_of_Love'],
 ['Shazam'],
 ['Puss_in_Boots'],
 ['Wonder_Woman'],
 ['Wonder_Woman'],
 ['Wonder_Woman'],
 ['42'],
 ['Life_of_Pi'],
 ['The_Crazies'],
 ['The_Equalizer'],
 ['Captain_America_The_First_Avenger'],
 ['Sin_City_A_Dame_to_Kill_For'],
 ['House_at_the_End_of_the_Drive'],
 ['Piranha_3D'],
 ['Margaret'],
 ['Ex_Machina'],
 ['Tower_Heist'],
 ['The_Smurfs'],
 ['The_Mechanic'],
 ['Hail_Caesar'],
 ['Unstoppable'],
 ['Unstoppable'],
 ['Unstoppable'],
 ['Unstoppable'],
 ['The_Tree_of_Life'],
 ['Ant-Man'],
 ['Season_of_the_Witch'],
 ['The_Losers'],
 ['The_Losers'],
 ['Hall_Pass'],
 ['The_Croods'],
 ['Barry_Munday'],
 ['Red_Tails'],
 ['Silence'],
 ['Silence'],
 ['Silence'],
 ['Silence'],
 ['Something_Borrowed'],
 ['Tulip_Fever'],
 ['Furry_Vengeance'],
 ['Ramona_and_Beezus'],
 ['Rings'],
 ['A_Thousand_Words'],
 ['Whats_Your_Number?'],
 ['Samsara'],
 ['Man_of_Steel'],
 ['The_Illusionist'],
 ['Drive'],
 ['Drive'],
 ['The_Wolfman'],
 ['The_Boxtrolls'],
 ['The_Man_Who_Knew_Infinity'],
 ['The_Incredible_Burt_Wonderstone'],
 ['Dallas_Buyers_Club'],
 ['Jack_Reacher'],
 ['RIPD'],
 ['Clash_of_the_Titans'],
 ['Clash_of_the_Titans'],
 ['Nemesis'],
 ['Thor'],
 ['Red_Dog'],
 ['Red_Dog'],
 ['Warcraft'],
 ['Its_Kind_of_a_Funny_Story'],
 ['The_Mule'],
 ['The_Mule'],
 ['The_Mule'],
 ['Tooth_Fairy'],
 ['Tooth_Fairy'],
 ['Jack_and_Jill'],
 ['Take_Me_Home_Tonight'],
 ['Percy_Jackson_&_the_Olympians_The_Lightning_Thief'],
 ['Shes_Out_of_My_League'],
 ['The_Book_Thief'],
 ['Conan_the_Barbarian'],
 ['Conan_the_Barbarian'],
 ['Interstellar'],
 ['World_War_Z'],
 ['Flipped'],
 ['Flipped'],
 ['Valentines_Day'],
 ['Priest'],
 ['Dracula_Untold'],
 ['Godzilla'],
 ['Godzilla'],
 ['Hotel_Transylvania'],
 ['Pet_Sematary'],
 ['Pet_Sematary'],
 ['The_Town'],
 ['The_Kids_Are_All_Right'],
 ['The_Avengers'],
 ['The_Avengers'],
 ['Epic'],
 ['Risen'],
 ['Risen'],
 ['The_Sweeney'],
 ['Mr_Peabody_&_Sherman'],
 ['My_Soul_to_Take'],
 ['Red_State'],
 ['Please_Give'],
 ['Eat_Pray_Love'],
 ['Sanctum'],
 ['Snitch'],
 ['Snitch'],
 ['The_Wedding_Ringer'],
 ['The_Switch'],
 ['Letters_to_Juliet'],
 ['How_to_Train_Your_Dragon'],
 ['Shrek_Forever_After'],
 ['The_Hobbit_An_Unexpected_Journey'],
 ['The_Thing'],
 ['The_Legend_of_Tarzan'],
 ['The_Dead_Undead'],
 ['Rabbit_Hole'],
 ['The_Last_Airbender'],
 ['Freaky_Deaky'],
 ['Salt'],
 ['Source_Code'],
 ['Black_Swan'],
 ['Green_Zone'],
 ['The_Amazing_Spider-Man'],
 ['The_Killer_Inside_Me'],
 ['Robin_Hood'],
 ['Robin_Hood'],
 ['Robin_Hood'],
 ['Robin_Hood'],
 ['Robin_Hood'],
 ['Robin_Hood'],
 ['Robin_Hood'],
 ['Robin_Hood'],
 ['Reach_Me'],
 ['Nine_Dead'],
 ['The_Sorcerers_Apprentice'],
 ['The_Fighter'],
 ['The_Conspirator'],
 ['Hugo'],
 ['Hugo'],
 ['Little_Fockers'],
 ['Justice_League'],
 ['Fair_Game'],
 ['Fair_Game'],
 ['Sucker_Punch'],
 ['Lottery_Ticket'],
 ['The_Chronicles_of_Narnia_The_Voyage_of_the_Dawn_Treader'],
 ['The_Adventures_of_Tintin'],
 ['Machete'],
 ['Dear_John'],
 ['Detention'],
 ['Detention'],
 ['The_Green_Hornet'],
 ['Hanna'],
 ['The_Wolf_of_Wall_Street'],
 ['Straw_Dogs'],
 ['Megamind'],
 ['The_Young_Messiah'],
 ['The_Iron_Lady'],
 ['The_Little_Prince'],
 ['The_Little_Prince'],
 ['The_Little_Prince'],
 ['Knight_and_Day'],
 ['Dylan_Dog_Dead_of_Night'],
 ['Alice_in_Wonderland'],
 ['Alice_in_Wonderland'],
 ['Alice_in_Wonderland'],
 ['Alice_in_Wonderland'],
 ['Child_44'],
 ['The_Sisterhood_of_Night'],
 ['The_Runaways'],
 ['The_Runaways'],
 ['Adam'],
 ['Adam'],
 ['Adam'],
 ['Adam'],
 ['Selma'],
 ['Centurion'],
 ['Argo'],
 ['Secretariat'],
 ['Poltergeist'],
 ['Poltergeist'],
 ['Kidnap'],
 ['Kidnap'],
 ['Hit_&_Run'],
 ['The_Warriors_Way'],
 ['The_Descendants'],
 ['The_Descendants'],
 ['The_Eagle'],
 ['Suspiria'],
 ['The_Book_of_Eli'],
 ['Legion'],
 ['The_Bounty_Hunter'],
 ['The_Bounty_Hunter'],
 ['The_Nutcracker_in_3D'],
 ['The_Legend_of_Hercules'],
 ['Silver_Linings_Playbook'],
 ['Parental_Guidance'],
 ['Goosebumps'],
 ['Repo_Men'],
 ['The_Big_Year'],
 ['Life_as_We_Know_It'],
 ['Boyhood'],
 ['Water_for_Elephants'],
 ['Monte_Carlo'],
 ['Footloose'],
 ['Footloose'],
 ['Good_Intentions'],
 ['Ghost_Rider_Spirit_of_Vengeance'],
 ['Winchester'],
 ['Skyfall'],
 ['Jonah_Hex'],
 ['Dark_Shadows'],
 ['The_Belko_Experiment'],
 ['Eddie_the_Eagle'],
 ['Lights_Out'],
 ['Lights_Out'],
 ['Lights_Out'],
 ['Lights_Out'],
 ['The_Prince'],
 ['Blended'],
 ['Lone_Survivor'],
 ['Noah'],
 ['Noah'],
 ['Noah'],
 ['Paul'],
 ['Paul'],
 ['Shanghai'],
 ['Shanghai'],
 ['The_Darkest_Hour'],
 ['The_Darkest_Hour'],
 ['The_Hammer'],
 ['The_Hammer'],
 ['Killers'],
 ['Killers'],
 ['Ca$h'],
 ['Ca$h'],
 ['Paddington'],
 ['Trance'],
 ['Trance'],
 ['Trance'],
 ['Trance'],
 ['Jackass_3D'],
 ['Blue_Valentine'],
 ['Seventh_Son'],
 ['The_Ides_of_March'],
 ['Free_State_of_Jones'],
 ['Love_Ranch'],
 ['Big_Eyes'],
 ['Big_Eyes'],
 ['Burlesque'],
 ['Burlesque'],
 ['Morning_Glory'],
 ['Circle'],
 ['Circle'],
 ['Shutter_Island'],
 ['The_5th_Quarter'],
 ['Green_Lantern'],
 ['Dwegons_and_Leprechauns'],
 ['Takers'],
 ['Death_Wish'],
 ['Accidental_Love'],
 ['The_Ghost_Writer'],
 ['Frankenweenie'],
 ['After'],
 ['After'],
 ['After'],
 ['After'],
 ['Beastly'],
 ['Freakonomics'],
 ['The_Joneses'],
 ['The_Joneses'],
 ['The_Karate_Kid'],
 ['The_Karate_Kid'],
 ['The_Rite'],
 ['Biutiful'],
 ['The_Hobbit_The_Desolation_of_Smaug'],
 ['Baggage_Claim'],
 ['All_Good_Things'],
 ['A_Walk_in_the_Woods'],
 ['A_Nightmare_on_Elm_Street'],
 ['A_Nightmare_on_Elm_Street'],
 ['10_Cloverfield_Lane'],
 ['Wuthering_Heights'],
 ['Wuthering_Heights'],
 ['You_Will_Meet_a_Tall_Dark_Stranger'],
 ['Welcome_to_the_Rileys'],
 ['The_Lincoln_Lawyer'],
 ['Rango'],
 ['Step_Up_3D'],
 ['The_Bourne_Legacy'],
 ['Casino_Jack'],
 ['The_Five-Year_Engagement'],
 ['Diary_of_a_Wimpy_Kid'],
 ['Pound_of_Flesh'],
 ['Pound_of_Flesh'],
 ['Pound_of_Flesh'],
 ['Gracie'],
 ['Kites'],
 ['The_Muppets'],
 ['Last_Vegas'],
 ['Ouija'],
 ['Jack_Ryan_Shadow_Recruit'],
 ['Out_of_the_Furnace'],
 ['Beyond_the_Mat'],
 ['Blood_Done_Sign_My_Name'],
 ['Moneyball'],
 ['The_Lone_Ranger'],
 ['Doctor_Strange'],
 ['Middle_of_Nowhere'],
 ['Escape_Plan'],
 ['The_Lion_of_Judah'],
 ['Hereafter'],
 ['The_Lost_City_of_Z'],
 ['The_Back-up_Plan'],
 ['Lawless'],
 ['First_Man'],
 ['First_Man'],
 ['The_Worlds_End'],
 ['Cars_2'],
 ['Kill_the_Messenger'],
 ['Leap_Year'],
 ['Leap_Year'],
 ['Womb'],
 ['Brave'],
 ['Limitless'],
 ['Limitless'],
 ['Limitless'],
 ['Legend_of_the_Guardians_The_Owls_of_GaHoole'],
 ['Ghost_in_the_Shell'],
 ['Resident_Evil_Afterlife'],
 ['Zookeeper'],
 ['Viy'],
 ['Get_Him_to_the_Greek'],
 ['Edge_of_Darkness'],
 ['The_Debt'],
 ['The_Debt'],
 ['Beautiful_Boy'],
 ['Beautiful_Boy'],
 ['Fat_Sick_&_Nearly_Dead'],
 ['Iron_Man_2'],
 ['Let_Me_In'],
 ['Let_Me_In'],
 ['Anchorman_2_The_Legend_Continues'],
 ['Collide'],
 ['Collide'],
 ['Same_Kind_of_Different_as_Me'],
 ['Due_Date'],
 ['Hot_Tub_Time_Machine'],
 ['Thats_My_Boy'],
 ['Drones'],
 ['Drones'],
 ['21_Jump_Street'],
 ['Brighton_Rock'],
 ['Ironclad'],
 ['Red_Dawn'],
 ['RoboCop'],
 ['RoboCop'],
 ['The_Future'],
 ['Wild_Target'],
 ['Broken_City'],
 ['Wind_Walkers'],
 ['Your_Highness'],
 ['Locker_13'],
 ['I_Spit_on_Your_Grave'],
 ['We_Need_to_Talk_About_Kevin'],
 ['The_Tourist'],
 ['Aloha'],
 ['Extraordinary_Measures'],
 ['Conviction'],
 ['Conviction'],
 ['Snatched'],
 ['Snatched'],
 ['Unforgettable'],
 ['Unforgettable'],
 ['Unforgettable'],
 ['Unforgettable'],
 ['Unforgettable'],
 ['Unforgettable'],
 ['Unforgettable'],
 ['Unforgettable'],
 ['High_School'],
 ['Kick-Ass'],
 ['Salvation_Boulevard'],
 ['300_Rise_of_an_Empire'],
 ['Immortals'],
 ['Daylight'],
 ['Daylight'],
 ['Daylight'],
 ['Holmes_&_Watson'],
 ['Incendies'],
 ['The_Man_with_the_Iron_Fists'],
 ['The_Cabin_in_the_Woods'],
 ['Den_of_Thieves'],
 ['Sex_and_the_City_2'],
 ['Scream_4'],
 ['The_Roommate'],
 ['Hercules'],
 ['Hercules'],
 ['Hercules'],
 ['Hercules'],
 ['A_Very_Harold_&_Kumar_3D_Christmas'],
 ['The_Devils_Double'],
 ['Dont_Be_Afraid_of_the_Dark'],
 ['Venom'],
 ['Venom'],
 ['Venom'],
 ['Venom'],
 ['X-Men_First_Class'],
 ['2_Guns'],
 ['Small_Apartments'],
 ['London_Fields'],
 ['The_Spy_Next_Door'],
 ['The_Tempest'],
 ['The_Tempest'],
 ['The_Tempest'],
 ['Dying_of_the_Light'],
 ['Looper'],
 ['Madagascar_3_Europes_Most_Wanted'],
 ['Date_Night'],
 ['Fort_McCoy'],
 ['Easy_A'],
 ['Bad_Teacher'],
 ['The_Strangers_Prey_at_Night'],
 ['The_Social_Network'],
 ['Cats_&_Dogs_The_Revenge_of_Kitty_Galore'],
 ['Evil_Dead'],
 ['Ghostbusters'],
 ['Ghostbusters'],
 ['N-Secure'],
 ['Teenage_Mutant_Ninja_Turtles'],
 ['Teenage_Mutant_Ninja_Turtles'],
 ['Warrior'],
 ['xXx_Return_of_Xander_Cage'],
 ['The_Last_Song'],
 ['The_FP'],
 ['Animals'],
 ['Animals'],
 ['Animals'],
 ['Animals'],
 ['The_Watch'],
 ['Pirates_of_the_Caribbean_On_Stranger_Tides'],
 ['Iron_Man_3'],
 ['Kung_Fu_Panda_2'],
 ['Yogi_Bear'],
 ['Standing_Ovation'],
 ['Our_Family_Wedding'],
 ['Mars_Needs_Moms'],
 ['5050'],
 ['5050'],
 ['Seeking_a_Friend_for_the_End_of_the_World'],
 ['Bullet_to_the_Head'],
 ['Animal_Kingdom'],
 ['3_Backyards'],
 ['Devil'],
 ['There_Be_Dragons'],
 ['Rise_of_the_Planet_of_the_Apes'],
 ['Its_a_Wonderful_Afterlife'],
 ['The_Last_Exorcism'],
 ['The_Expendables'],
 ['Gullivers_Travels'],
 ['The_Reef'],
 ['Death_at_a_Funeral'],
 ['Death_at_a_Funeral'],
 ['Oldboy'],
 ['The_Beaver'],
 ['The_Lovers'],
 ['The_Lovers'],
 ['Gangster_Squad'],
 ['August_Osage_County'],
 ['Going_the_Distance'],
 ['Going_the_Distance'],
 ['Frozen'],
 ['Frozen'],
 ['Frozen'],
 ['Despicable_Me'],
 ['The_Twilight_Saga_Eclipse'],
 ['The_Lucky_One'],
 ['Something_Wicked'],
 ['Cyrus'],
 ['Cyrus'],
 ['Lee_Daniels_The_Butler'],
 ['Death_Calls'],
 ['The_Apostle'],
 ['The_Apostle'],
 ['Movie_43'],
 ['Never_Let_Me_Go'],
 ['Arthur'],
 ['Bad_Company'],
 ['Bad_Company'],
 ['The_Perfect_Host'],
 ['The_Perfect_Host'],
 ['47_Ronin'],
 ['Rock_of_Ages'],
 ['Tinker_Tailor_Soldier_Spy'],
 ['Four_Lions'],
 ['Butterfly'],
 ['Butterfly'],
 ['Butterfly'],
 ['The_Great_Gatsby'],
 ['The_Great_Gatsby'],
 ['Dredd'],
 ['The_Dark_Knight_Rises'],
 ['Redemption'],
 ['Redemption'],
 ['Redemption'],
 ['Redemption'],
 ['Redemption'],
 ['Jack_the_Giant_Slayer'],
 ['If_I_Stay'],
 ['The_Infiltrator'],
 ['Passengers'],
 ['Black_Mass'],
 ['Rust'],
 ['Rust'],
 ['Rust'],
 ['Rust'],
 ['The_Extra_Man'],
 ['Tomb_Raider'],
 ['Lowriders'],
 ['The_Sitter'],
 ['The_Sitter'],
 ['The_Cold_Light_of_Day'],
 ['Cloud_Atlas'],
 ['Made_in_Dagenham'],
 ['The_Kid'],
 ['The_Kid'],
 ['The_Kid'],
 ['Coriolanus'],
 ['Coriolanus'],
 ['Stranded'],
 ['Stranded'],
 ['Stranded'],
 ['The_Awakening'],
 ['The_Awakening'],
 ['Pride_and_Prejudice_and_Zombies'],
 ['Upside_Down'],
 ['Upside_Down'],
 ['Upside_Down'],
 ['Inception'],
 ['Grown_Ups'],
 ['Gunless'],
 ['The_Adventurer_The_Curse_of_the_Midas_Box'],
 ['The_Adjustment_Bureau'],
 ['Cop_Out'],
 ['The_Other_Guys'],
 ['Suicide_Squad'],
 ['Total_Recall'],
 ['Total_Recall'],
 ['Downsizing'],
 ['We_Bought_a_Zoo'],
 ['When_the_Bough_Breaks'],
 ['When_the_Bough_Breaks'],
 ['In_the_Heart_of_the_Sea'],
 ['The_Lost_Medallion_The_Adventures_of_Billy_Stone'],
 ['Why_Did_I_Get_Married_Too?'],
 ['The_Hunger_Games'],
 ['Mad_Max_Fury_Road'],
 ['Marmaduke'],
 ['Prisoners'],
 ['It'],
 ['Taken_2'],
 ['Journey_2_The_Mysterious_Island'],
 ['Straight_Outta_Compton'],
 ['Transformers_Dark_of_the_Moon'],
 ['Winters_Bone'],
 ['Unknown'],
 ['Unknown'],
 ['Unknown'],
 ['Unknown'],
 ['Happy_Feet_Two'],
 ['Hesher'],
 ['Wolves'],
 ['Wolves'],
 ['True_Grit'],
 ['Remember_Me'],
 ['Remember_Me'],
 ['For_Colored_Girls'],
 ['Just_Wright'],
 ['Star_Trek_Into_Darkness'],
 ['Ride_Along'],
 ['Ride_Along'],
 ['Men_in_Black_3'],
 ['Beloved'],
 ['Beloved'],
 ['Beloved'],
 ['Beloved'],
 ['No_Strings_Attached'],
 ['Riddick'],
 ['Bucky_Larson_Born_to_Be_a_Star'],
 ['The_Hangover_Part_II'],
 ['Hop'],
 ['The_Best_Exotic_Marigold_Hotel'],
 ['Table_19'],
 ['12_Strong'],
 ['Paranoia'],
 ['Paranoia'],
 ['Tracker'],
 ['You_Again'],
 ['Kill_the_Irishman'],
 ['I_Frankenstein'],
 ['Beneath_Hill_60'],
 ['Somewhere'],
 ['A_Lonely_Place_to_Die'],
 ['Barneys_Version'],
 ['Stone'],
 ['Stone'],
 ['Predators'],
 ['Black_Nativity'],
 ['Hansel_&_Gretel_Witch_Hunters'],
 ['The_Wolverine'],
 ['Arthur_Christmas'],
 ['Brick_Mansions'],
 ['Big_Miracle'],
 ['Payback'],
 ['Payback'],
 ['Payback'],
 ['The_Pirates_Band_of_Misfits'],
 ['Deadline'],
 ['Deadline'],
 ['Deadline'],
 ['Deadpool'],
 ['Forget_Me_Not'],
 ['Forget_Me_Not'],
 ['Forget_Me_Not'],
 ['Forget_Me_Not'],
 ['Forget_Me_Not'],
 ['Forget_Me_Not'],
 ['Another_Year'],
 ['Another_Year'],
 ['Another_Year'],
 ['Faster'],
 ['Sleeper'],
 ['The_Apparition'],
 ['The_Apparition'],
 ['Firestorm'],
 ['Firestorm'],
 ['Rio'],
 ['Rio'],
 ['Rio'],
 ['Bait'],
 ['Bait'],
 ['Bait'],
 ['Fright_Night'],
 ['Charlie_St_Cloud'],
 ['Battleship'],
 ['A_Little_Bit_of_Heaven'],
 ['Submarine'],
 ['The_American'],
 ['Martha_Marcy_May_Marlene'],
 ['Under_the_Skin'],
 ['Quartet'],
 ['Testament_of_Youth'],
 ['Rise_of_the_Guardians'],
 ['Prometheus'],
 ['Bones'],
 ['My_Girlfriends_Boyfriend'],
 ['Killer_Elite'],
 ['Winnie_the_Pooh'],
 ['Monsters_University'],
 ['The_Help'],
 ['Gravity'],
 ['The_Wall'],
 ['The_Wall'],
 ['The_Wall'],
 ['The_Wall'],
 ['No_Mans_Land'],
 ['No_Mans_Land'],
 ['The_Conjuring'],
 ['The_Next_Three_Days'],
 ['Reign_of_Assassins'],
 ['Henry_&_Me'],
 ['Dream_House'],
 ['Letters_to_God'],
 ['Buried'],
 ['Buried'],
 ['The_Odd_Life_of_Timothy_Green'],
 ['Big_Mommas_Like_Father_Like_Son'],
 ['Stake_Land'],
 ['Joy'],
 ['Joy'],
 ['Joy'],
 ['Joy'],
 ['Joy'],
 ['Baywatch'],
 ['Redemption_Road'],
 ['MacGruber'],
 ['Monsters'],
 ['Monsters'],
 ['Max_Steel'],
 ['Aquaman'],
 ['Cedar_Rapids'],
 ['Bridesmaids'],
 ['Attack_the_Block'],
 ['Eddie_The_Sleepwalking_Cannibal'],
 ['Logan'],
 ['Logan'],
 ['Oblivion'],
 ['Oblivion'],
 ['8_The_Mormon_Proposition'],
 ['The_Greatest_Showman'],
 ['Red_Riding_Hood'],
 ['The_Raven'],
 ['5_Days_of_War'],
 ['Khumba'],
 ['Zambezia'],
 ['The_Change-Up'],
 ['The_Forest'],
 ['The_Forest'],
 ['The_Forest'],
 ['The_Forest'],
 ['Central_Intelligence'],
 ['The_Lego_Movie'],
 ['The_Iceman'],
 ['Foreign_Letters'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Gift'],
 ['The_Paperboy'],
 ['Red_River'],
 ['Restless'],
 ['Restless'],
 ['Horrible_Bosses'],
 ['Vampires'],
 ['Drive_Angry'],
 ['Halloween'],
 ['Halloween'],
 ['Halloween'],
 ['Fantastic_Four'],
 ['Fantastic_Four'],
 ['Haywire'],
 ['Cargo'],
 ['Cargo'],
 ['Cargo'],
 ['Cargo'],
 ['Le_Havre'],
 ['The_Three_Musketeers'],
 ['The_Three_Musketeers'],
 ['Griff_the_Invisible'],
 ['Super'],
 ['Super'],
 ['Sherlock_Holmes_A_Game_of_Shadows'],
 ['3'],
 ['3'],
 ['3'],
 ['3'],
 ['The_Host'],
 ['The_Host'],
 ['Meeks_Cutoff'],
 ['Area_51'],
 ['Anonymous'],
 ['Limbo'],
 ['Limbo'],
 ['A_True_Story'],
 ['Contraband'],
 ['The_Vatican_Tapes'],
 ['Vacation'],
 ['Grabbers'],
 ['Melancholia'],
 ['Melancholia'],
 ['Hero'],
 ['Hero'],
 ['Hero'],
 ['Hero'],
 ['Exodus_Gods_and_Kings'],
 ['Sea_Rex_3D_Journey_to_a_Prehistoric_World'],
 ['Trust'],
 ['Trust'],
 ['Trust'],
 ['Everything_Must_Go'],
 ['Beginners'],
 ['Battle_of_the_Year'],
 ['Beyond_the_Black_Rainbow'],
 ['Elysium'],
 ['Elysium'],
 ['Captain_Phillips'],
 ['Hope_Springs'],
 ['The_Son_of_No_One'],
 ['The_Divide'],
 ['The_Divide'],
 ['The_Divide'],
 ['Paranormal_Activity_2'],
 ['The_Mortal_Instruments_City_of_Bones'],
 ['Blair_Witch'],
 ['Playing_for_Keeps'],
 ['The_Guard'],
 ['Snow_Flower_and_the_Secret_Fan'],
 ['127_Hours'],
 ['The_Grace_Card'],
 ['Vamps'],
 ['Vamps'],
 ['Point_Blank'],
 ['Point_Blank'],
 ['Without_Men'],
 ['Premium_Rush'],
 ['Another_Earth'],
 ['The_Last_Stand'],
 ['Winnie_Mandela'],
 ['A_Better_Life'],
 ['A_Better_Life'],
 ['Born_of_War'],
 ['Country_Strong'],
 ['Mary_Queen_of_Scots'],
 ['Mary_Queen_of_Scots'],
 ['Grace'],
 ['Grace'],
 ['Grace'],
 ['Beautiful_Creatures'],
 ['The_Master'],
 ['The_Master'],
 ['The_Master'],
 ['I_Want_Your_Money'],
 ['The_Devil_Inside'],
 ['Higher_Ground'],
 ['Amigo'],
 ['One_Day'],
 ['One_Day'],
 ['One_Day'],
 ['One_Day'],
 ['One_Day'],
 ['One_Day'],
 ['Overboard'],
 ['Contact'],
 ['Contact'],
 ['Dolphin_Tale'],
 ['Skyline'],
 ['Head_Over_Heels'],
 ['For_Greater_Glory_The_True_Story_of_Cristiada'],
 ['Man_on_a_Ledge'],
 ['Some_Guy_Who_Kills_People'],
 ['The_Girl_with_the_Dragon_Tattoo'],
 ['War_Horse'],
 ['War_Horse'],
 ['Closure'],
 ['Closure'],
 ['Closure'],
 ['Closure'],
 ['Closure'],
 ['Tiny_Furniture'],
 ['A_Dangerous_Method'],
 ['Mortal_Engines'],
 ['The_Skeleton_Twins'],
 ['Honey'],
 ['Honey'],
 ['Honey'],
 ['Texas_Chainsaw_3D'],
 ['Housefull'],
 ['Housefull'],
 ['The_Hit_List'],
 ['Skin_Trade'],
 ['Skin_Trade'],
 ['The_Dilemma'],
 ['House_at_the_End_of_the_Street'],
 ['Larry_Crowne'],
 ['GI_Joe_Retaliation'],
 ['The_Last_Godfather'],
 ['Severance'],
 ['What_to_Expect_When_Youre_Expecting'],
 ['Machine_Gun_Preacher'],
 ['Maleficent'],
 ['Warm_Bodies'],
 ['Jeff_Who_Lives_at_Home'],
 ['Brother'],
 ['Brother'],
 ['The_Commuter'],
 ['Insidious'],
 ['Act_of_Valor'],
 ['Lockout'],
 ['LOL'],
 ['The_Innkeepers'],
 ['Norm_of_the_North'],
 ['Fast_Five'],
 ['Soul_Surfer'],
 ['This_Means_War'],
 ['The_Big_Short'],
 ['The_Woman_in_Black'],
 ['Click'],
 ['Contagion'],
 ['One_for_the_Money'],
 ['Safe_House'],
 ['Sonny'],
 ['Abduction'],
 ['Abduction'],
 ['Abduction'],
 ['Abduction'],
 ['The_Drop'],
 ['The_Grey'],
 ['Albert_Nobbs'],
 ['Only_God_Forgives'],
 ['Amour'],
 ['A_Fine_Step'],
 ['Prom'],
 ['American_Reunion'],
 ['The_Visit'],
 ['The_Visit'],
 ['Midnight_in_Paris'],
 ['A_Good_Day_to_Die_Hard'],
 ['The_Vow'],
 ['Iris'],
 ['Iris'],
 ['The_Other_Dream_Team'],
 ['Zoolander_2'],
 ['Three_Kings'],
 ['Three_Kings'],
 ['Absentia'],
 ['Abraham_Lincoln_Vampire_Hunter'],
 ['Re-Kill'],
 ['Rubber'],
 ['Savages'],
 ['Margin_Call'],
 ['The_Foreigner'],
 ['The_Foreigner'],
 ['Alvin_and_the_Chipmunks_Chipwrecked'],
 ['J_Edgar'],
 ['Monster'],
 ['Monster'],
 ['Monster'],
 ['Monster'],
 ['Jupiter_Ascending'],
 ['Dum_Maaro_Dum'],
 ['The_Last_Witch_Hunter'],
 ['Jackie'],
 ['Jackie'],
 ['Jackie'],
 ['A_Wrinkle_in_Time'],
 ['Bleed_for_This'],
 ['Free_Birds'],
 ['Think_Like_a_Man'],
 ['30_Minutes_or_Less'],
 ['Final_Destination_5'],
 ['Infected'],
 ['Infected'],
 ['Oz_the_Great_and_Powerful'],
 ['ParaNorman'],
 ['Stitches'],
 ['Stitches'],
 ['Stitches'],
 ['Stitches'],
 ['Young_Adult'],
 ['The_Journey'],
 ['The_Journey'],
 ['The_Journey'],
 ['The_Journey'],
 ['The_Journey'],
 ['Independence_Day_Resurgence'],
 ['Blackthorn'],
 ['Chasing_Mavericks'],
 ['Courageous'],
 ['Enter_Nowhere'],
 ['Edge_of_Tomorrow'],
 ['Creed'],
 ['Creed'],
 ['Creed'],
 ['Friends_with_Benefits'],
 ['Shark_Night_3D'],
 ['Dragonslayer'],
 ['Underdogs'],
 ['Underdogs'],
 ['Johnny_English_Reborn'],
 ['The_Intern'],
 ['The_Intern'],
 ['Project_X'],
 ['Black_and_White'],
 ['In_Time'],
 ...]

In [12]:
R = requests.get('https://www.rottentomatoes.com/m/foodfight')

In [218]:
"""for title in new_list:
    R = requests.get('https://www.rottentomatoes.com/m/{}'.format(title))
    if R.status_code == 404:
        continue 
    elif R.status_code == 500:
        continue 
        
"""

"for title in new_list:\n    R = requests.get('https://www.rottentomatoes.com/m/{}'.format(title))\n    if R.status_code == 404:\n        continue \n    elif R.status_code == 500:\n        continue \n        \n"

In [13]:
R.status_code

200

In [ ]:
#R.text

In [14]:
soup = BeautifulSoup(R.text, 'html.parser')

In [15]:
#for review in reviews:
    print(review,'\n')

IndentationError: unexpected indent (<ipython-input-15-9970f29d89e7>, line 2)

In [16]:
#collect the div content 

divs = soup.findAll(class_='media-body quote_bubble__quote')

In [225]:
#print(divs_title)

In [17]:
#display all the reviews 

reviews = []
for div in divs:
    div.find('p').text, '\n'

In [18]:
for div in divs:
    reviews.append(div.find('p').text)

In [19]:
#Needed to get rid of the new line characters 

clean_reviews = []

for x in reviews:
    clean_reviews.append(x.strip())

In [20]:
#clean_reviews

In [21]:
reviews_df = pd.DataFrame(np.array(clean_reviews), columns = ['review'])

In [22]:
reviews_df.head()

                                              review
0  Odd adventure-comedy has lots of innuendo, car...
1  The absolute ugliest animated feature that has...

In [23]:
movie_df.head()

,Unnamed: 0,Unnamed: 0.1,tconst,primary_title,runtime_minutes,genres,averagerating,numvotes,id,production_budget,domestic_gross,worldwide_gross,release_month,release_day,release_year
0,0,0,tt0249516,Foodfight,91.0,"Action,Animation,Comedy",1.9,8248,26,45000000,0,73706,Dec,31,2012
1,1,1,tt0326592,The_Overnight,88.0,NaN,7.5,24,21,200000,1109808,1165996,Jun,19,2015
2,2,2,tt3844362,The_Overnight,79.0,"Comedy,Mystery",6.1,14828,21,200000,1109808,1165996,Jun,19,2015
3,3,3,tt0337692,On_the_Road,124.0,"Adventure,Drama,Romance",6.1,37886,17,25000000,720828,9313302,Mar,22,2013
4,4,4,tt4339118,On_the_Road,89.0,Drama,6.0,6,17,25000000,720828,9313302,Mar,22,2013

In [24]:
reviews_df.head()

                                              review
0  Odd adventure-comedy has lots of innuendo, car...
1  The absolute ugliest animated feature that has...

In [25]:
#Gather the word length of each review

reviews_df['word_count'] = reviews_df['review'].apply(lambda x: len(x.split()))

In [26]:
#Gather the character count of each review

reviews_df['char_count'] = reviews_df['review'].apply(lambda x: len(x))

In [27]:
#Create a function to gather average number of words per review

def average_words(x):
    words = x.split() #to give the # of words
    return sum(len(word)for word in words) / len(words)

In [28]:
reviews_df['average_word_length'] = reviews_df['review'].apply(lambda x: average_words(x))

In [238]:
#reviews_df.head()

In [29]:
#starting sentiment analysis 

import nltk
from nltk.corpus import stopwords

In [30]:
stop_words = stopwords.words('english')

len(stop_words)

179

In [31]:
#How many stop words in each review 

reviews_df['stopword_count'] = reviews_df['review'].apply(lambda x: len([word for word in x.split() if word in stop_words]))

In [32]:
reviews_df['stopword_percentage'] = reviews_df['stopword_count']/reviews_df['word_count']

In [33]:

#reviews_df['movie_name'] = new_list[title]

In [34]:
reviews_df.sort_values(by = 'stopword_percentage')

,review,word_count,char_count,average_word_length,stopword_count,stopword_percentage
0,"Odd adventure-comedy has lots of innuendo, car...",8,59,6.500000,2,0.250000
1,The absolute ugliest animated feature that has...,17,117,5.941176,5,0.294118

In [35]:
reviews_df.head()

,review,word_count,char_count,average_word_length,stopword_count,stopword_percentage
0,"Odd adventure-comedy has lots of innuendo, car...",8,59,6.500000,2,0.250000
1,The absolute ugliest animated feature that has...,17,117,5.941176,5,0.294118

In [36]:
reviews_df.describe()

,word_count,char_count,average_word_length,stopword_count,stopword_percentage
count,2.000000,2.000000,2.000000,2.00000,2.000000
mean,12.500000,88.000000,6.220588,3.50000,0.272059
std,6.363961,41.012193,0.395148,2.12132,0.031196
min,8.000000,59.000000,5.941176,2.00000,0.250000
25%,10.250000,73.500000,6.080882,2.75000,0.261029
50%,12.500000,88.000000,6.220588,3.50000,0.272059
75%,14.750000,102.500000,6.360294,4.25000,0.283088
max,17.000000,117.000000,6.500000,5.00000,0.294118

In [37]:
#Data Cleaning 

#looping through each word which is x
#splititng x givng us every word
#every word we get back were lowering

reviews_df['lowercase'] = reviews_df['review'].apply(lambda x: " ".join(word.lower() for word in x.split()))

In [38]:
#removing puncuations

reviews_df['punctuation'] = reviews_df['lowercase'].str.replace('[^\w\s]', '')

In [39]:
reviews_df['stopwords'] = reviews_df['punctuation'].apply(lambda x: " ".join(word for word in x.split() if word not in stop_words))

In [40]:
#other words that dont add value

other_stopwords = ['us','get','also','would','end','hill']

In [41]:
reviews_df['clean_review'] = reviews_df['stopwords'].apply(lambda x: " ".join(word for word in x.split() if word not in other_stopwords))

In [42]:
#an array of every single word in all the reviews

pd.Series(" ".join(reviews_df['clean_review']).split()).value_counts()[:30]

odd                1
ugliest            1
studio             1
lots               1
absolute           1
ever               1
feature            1
animation          1
animated           1
innuendo           1
cartoon            1
something          1
released           1
actual             1
resembling         1
violence           1
adventurecomedy    1
dtype: int64

In [43]:
#Lemmatization
#Basically changing word like resturants to resturant(words to word) bc really they mean the same thing 

import textblob

from textblob import Word

from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer()

In [44]:
reviews_df['lemmatized'] = reviews_df['clean_review'].apply(lambda x: " ".join(Word(word).lemmatize() for word in x.split()))

In [45]:
#Sentiment Analysis

from textblob import TextBlob

In [46]:
reviews_df['polarity'] = reviews_df['lemmatized'].apply(lambda x: TextBlob(x).sentiment[0])

In [47]:
reviews_df['subjectivity'] = reviews_df['lemmatized'].apply(lambda x: TextBlob(x).sentiment[1])

In [48]:
#clean up columns we dont need now

reviews_df.drop(['lowercase','punctuation','stopwords','clean_review', 'lemmatized'], axis = 1, inplace = True)

In [49]:
reviews_df.head()

,review,word_count,char_count,average_word_length,stopword_count,stopword_percentage,polarity,subjectivity
0,"Odd adventure-comedy has lots of innuendo, car...",8,59,6.500000,2,0.250000,-0.166667,0.25
1,The absolute ugliest animated feature that has...,17,117,5.941176,5,0.294118,0.100000,0.50

In [50]:
#average ppolarity for X Movie

reviews_df['polarity'].mean()

-0.033333333333333326

In [51]:
reviews_df['total_polarity'] = reviews_df.polarity.mean()

In [52]:
reviews_df.head()

,review,word_count,char_count,average_word_length,stopword_count,stopword_percentage,polarity,subjectivity,total_polarity
0,"Odd adventure-comedy has lots of innuendo, car...",8,59,6.500000,2,0.250000,-0.166667,0.25,-0.033333
1,The absolute ugliest animated feature that has...,17,117,5.941176,5,0.294118,0.100000,0.50,-0.033333

In [59]:
#set primary_title to the movie name and primary_title in movie_df so i can merge them

reviews_df['primary_title'] = movie_df['primary_title'][count]

KeyError: 2875

In [54]:
reviews_df.head()

,review,word_count,char_count,average_word_length,stopword_count,stopword_percentage,polarity,subjectivity,total_polarity,primary_title
0,"Odd adventure-comedy has lots of innuendo, car...",8,59,6.500000,2,0.250000,-0.166667,0.25,-0.033333,Foodfight
1,The absolute ugliest animated feature that has...,17,117,5.941176,5,0.294118,0.100000,0.50,-0.033333,Foodfight

In [63]:
full_movie_df = pd.merge(movie_df, reviews_df, on = "primary_title")
full_movie_df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'tconst', 'primary_title',
       'runtime_minutes', 'genres', 'averagerating', 'numvotes', 'id',
       'production_budget', 'domestic_gross', 'worldwide_gross',
       'release_month', 'release_day', 'release_year', 'review', 'word_count',
       'char_count', 'average_word_length', 'stopword_count',
       'stopword_percentage', 'polarity', 'subjectivity', 'total_polarity'],
      dtype='object')

In [64]:
full_movie_df.head()

,Unnamed: 0,Unnamed: 0.1,tconst,primary_title,runtime_minutes,genres,averagerating,numvotes,id,production_budget,...,release_year,review,word_count,char_count,average_word_length,stopword_count,stopword_percentage,polarity,subjectivity,total_polarity
0,0,0,tt0249516,Foodfight,91.0,"Action,Animation,Comedy",1.9,8248,26,45000000,...,2012,"Odd adventure-comedy has lots of innuendo, car...",8,59,6.500000,2,0.250000,-0.166667,0.25,-0.033333
1,0,0,tt0249516,Foodfight,91.0,"Action,Animation,Comedy",1.9,8248,26,45000000,...,2012,The absolute ugliest animated feature that has...,17,117,5.941176,5,0.294118,0.100000,0.50,-0.033333

In [65]:
movie_df.head()

,Unnamed: 0,Unnamed: 0.1,tconst,primary_title,runtime_minutes,genres,averagerating,numvotes,id,production_budget,domestic_gross,worldwide_gross,release_month,release_day,release_year
0,0,0,tt0249516,Foodfight,91.0,"Action,Animation,Comedy",1.9,8248,26,45000000,0,73706,Dec,31,2012
1,1,1,tt0326592,The_Overnight,88.0,NaN,7.5,24,21,200000,1109808,1165996,Jun,19,2015
2,2,2,tt3844362,The_Overnight,79.0,"Comedy,Mystery",6.1,14828,21,200000,1109808,1165996,Jun,19,2015
3,3,3,tt0337692,On_the_Road,124.0,"Adventure,Drama,Romance",6.1,37886,17,25000000,720828,9313302,Mar,22,2013
4,4,4,tt4339118,On_the_Road,89.0,Drama,6.0,6,17,25000000,720828,9313302,Mar,22,2013